# sudo docker logs -f transmission
version: "3.7"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission-pi
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Kiev 
    volumes:
      - /plex-media/transmission-config:/config 
      - /plex-media/movie:/downloads/complete
      - /plex-media/incomplete:/downloads/incomplete
    ports:
      - 9091:9091 
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
# plex      
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-pi
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /plex-media/config:/config
      - /plex-media/tv:/tv
      - /plex-media/movie:/movies
    restart: unless-stopped 
# portainer
  portainer:
    image: portainer/portainer-ce:2.17.0 # Replace 2.11.0 with the latest version.
    container_name: portainer-pi
    command: -H unix:///var/run/docker.sock
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /partainer:/data
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    restart: unless-stopped
# portainer-agent for prometheus
  portainer-agent:
    image: portainer/agent:2.17.0 # Replace 2.11.0 with the latest version, will be math with main portainer version
    container_name: portainer-agent-pi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
#heimdall
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall-pi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Kiev
    volumes:
      - /heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  jenkins:
    image: root/jenkins
    container_name: jenkins-pi
    command:
      - '--httpPort=8081' #custom web port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Kiev
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - 8081:8081
      - 50000:50000
    restart: unless-stopped
# node exporter for prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter-pi
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
# cAdvisor for prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor-pi
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped