version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
# for successfully  Prometheus up, use 0777 permission for data folder: ~ sudo chmod 0777 -R /prometheus-data/
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - /prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
# if your have error in contaiber log ~'/var/lib/grafana/plugins': Permission denied
# id -u
# sudo chown -R 1000:1000 /prometheus-data/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /grafana-data:/var/lib/grafana
    user: "1000"
    restart: unless-stopped
# node exporter for prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter-pi
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
#for correct ram monitoring on raspberry pi 4
#sudo nano /boot/cmdline.txt
#// add at the end of the line:
#cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
#// save file
# cAdvisor for prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.46.0
    container_name: cadvisor-pi
    privileged: true
    stdin_open: true
    tty: true
    command:
      - "--housekeeping_interval=30s"
#      - "--docker_only=true"
#      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl"
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /proc/cgroups:/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
# portainer-agent for prometheus
  portainer-agent:
    image: portainer/agent:2.17.0 # Replace 2.11.0 with the latest version, will be math with main portainer version
    container_name: portainer-agent-pi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped